[2022-10-01 20:17:31,506] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.create_fct_table manual__2022-10-01T20:16:54.766859+00:00 [queued]>
[2022-10-01 20:17:31,524] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.create_fct_table manual__2022-10-01T20:16:54.766859+00:00 [queued]>
[2022-10-01 20:17:31,525] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 20:17:31,526] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-01 20:17:31,526] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 20:17:31,557] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_fct_table> on 2022-10-01 20:16:54.766859+00:00
[2022-10-01 20:17:31,564] {standard_task_runner.py:52} INFO - Started process 1491 to run task
[2022-10-01 20:17:31,575] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_fct_table', 'manual__2022-10-01T20:16:54.766859+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpl6_73r7t', '--error-file', '/tmp/tmpbf62lk0e']
[2022-10-01 20:17:31,576] {standard_task_runner.py:80} INFO - Job 84: Subtask create_fct_table
[2022-10-01 20:17:31,678] {task_command.py:369} INFO - Running <TaskInstance: main_dag.create_fct_table manual__2022-10-01T20:16:54.766859+00:00 [running]> on host cb37a969dddb
[2022-10-01 20:17:31,825] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_fct_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T20:16:54.766859+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-01T20:16:54.766859+00:00
[2022-10-01 20:17:31,841] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-01 20:17:31,846] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS fct_table (
                Market_Cap TEXT NOT NULL,
                Last_Price TEXT NOT NULL,
                Priceâ€“earnings_ratio TEXT NOT NULL,
                Dividend_yield TEXT NOT NULL,
                Return_on_equity TEXT NOT NULL,
                Company_Key TEXT NOT NULL,
                Stock_Key TEXT NOT NULL
            );
        , parameters: None
[2022-10-01 20:17:31,850] {postgres.py:94} INFO - NOTICE:  relation "fct_table" already exists, skipping

[2022-10-01 20:17:31,868] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_fct_table, execution_date=20221001T201654, start_date=20221001T201731, end_date=20221001T201731
[2022-10-01 20:17:31,907] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-01 20:17:32,006] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
