[2022-10-01 19:37:46,320] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.create_company_dim_table manual__2022-10-01T19:36:24.220735+00:00 [queued]>
[2022-10-01 19:37:46,346] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.create_company_dim_table manual__2022-10-01T19:36:24.220735+00:00 [queued]>
[2022-10-01 19:37:46,347] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 19:37:46,348] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-01 19:37:46,348] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 19:37:46,403] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_company_dim_table> on 2022-10-01 19:36:24.220735+00:00
[2022-10-01 19:37:46,417] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_company_dim_table', 'manual__2022-10-01T19:36:24.220735+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp_r2v1r02', '--error-file', '/tmp/tmpsdxrc35t']
[2022-10-01 19:37:46,423] {standard_task_runner.py:80} INFO - Job 50: Subtask create_company_dim_table
[2022-10-01 19:37:46,413] {standard_task_runner.py:52} INFO - Started process 133 to run task
[2022-10-01 19:37:46,602] {task_command.py:369} INFO - Running <TaskInstance: main_dag.create_company_dim_table manual__2022-10-01T19:36:24.220735+00:00 [running]> on host cb37a969dddb
[2022-10-01 19:37:46,922] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_company_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T19:36:24.220735+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-01T19:36:24.220735+00:00
[2022-10-01 19:37:46,944] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-01 19:37:46,949] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS company_dim_table (
                Company_Full_Name TEXT NOT NULL,
                Last_Price TEXT NOT NULL,
                Shariah TEXT NOT NULL,
                Sector TEXT NOT NULL,
                Company_Key TEXT NOT NULL
            );
        , parameters: None
[2022-10-01 19:37:46,951] {postgres.py:94} INFO - NOTICE:  relation "company_dim_table" already exists, skipping

[2022-10-01 19:37:46,980] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_company_dim_table, execution_date=20221001T193624, start_date=20221001T193746, end_date=20221001T193746
[2022-10-01 19:37:47,057] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-01 19:37:47,173] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
