[2022-10-01 21:32:54,594] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.create_fct_table manual__2022-10-01T21:32:03.588736+00:00 [queued]>
[2022-10-01 21:32:54,608] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.create_fct_table manual__2022-10-01T21:32:03.588736+00:00 [queued]>
[2022-10-01 21:32:54,609] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 21:32:54,609] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-01 21:32:54,609] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 21:32:54,628] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_fct_table> on 2022-10-01 21:32:03.588736+00:00
[2022-10-01 21:32:54,634] {standard_task_runner.py:52} INFO - Started process 126 to run task
[2022-10-01 21:32:54,638] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_fct_table', 'manual__2022-10-01T21:32:03.588736+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmprldx7yir', '--error-file', '/tmp/tmpgynqj2_u']
[2022-10-01 21:32:54,639] {standard_task_runner.py:80} INFO - Job 111: Subtask create_fct_table
[2022-10-01 21:32:54,708] {task_command.py:369} INFO - Running <TaskInstance: main_dag.create_fct_table manual__2022-10-01T21:32:03.588736+00:00 [running]> on host 8fa0dcc1c8f5
[2022-10-01 21:32:54,808] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_fct_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T21:32:03.588736+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-01T21:32:03.588736+00:00
[2022-10-01 21:32:54,823] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-01 21:32:54,828] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS fct_table (
                Market_Cap TEXT NOT NULL,
                Last_Price TEXT NOT NULL,
                Priceâ€“earnings_ratio TEXT NOT NULL,
                Dividend_yield TEXT NOT NULL,
                Return_on_equity TEXT NOT NULL,
                Company_Key TEXT NOT NULL,
                Stock_Key TEXT NOT NULL
            );
        , parameters: None
[2022-10-01 21:32:54,830] {postgres.py:94} INFO - NOTICE:  relation "fct_table" already exists, skipping

[2022-10-01 21:32:54,855] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_fct_table, execution_date=20221001T213203, start_date=20221001T213254, end_date=20221001T213254
[2022-10-01 21:32:54,892] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-01 21:32:54,949] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
