[2022-10-01 20:50:37,023] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.create_company_dim_table manual__2022-10-01T20:49:23.320330+00:00 [queued]>
[2022-10-01 20:50:37,041] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.create_company_dim_table manual__2022-10-01T20:49:23.320330+00:00 [queued]>
[2022-10-01 20:50:37,041] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 20:50:37,042] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-01 20:50:37,042] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 20:50:37,062] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_company_dim_table> on 2022-10-01 20:49:23.320330+00:00
[2022-10-01 20:50:37,068] {standard_task_runner.py:52} INFO - Started process 2450 to run task
[2022-10-01 20:50:37,073] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_company_dim_table', 'manual__2022-10-01T20:49:23.320330+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpdlpmi0rb', '--error-file', '/tmp/tmpzndvie2t']
[2022-10-01 20:50:37,074] {standard_task_runner.py:80} INFO - Job 105: Subtask create_company_dim_table
[2022-10-01 20:50:37,146] {task_command.py:369} INFO - Running <TaskInstance: main_dag.create_company_dim_table manual__2022-10-01T20:49:23.320330+00:00 [running]> on host cb37a969dddb
[2022-10-01 20:50:37,275] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_company_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T20:49:23.320330+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-01T20:49:23.320330+00:00
[2022-10-01 20:50:37,294] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-01 20:50:37,303] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS company_dim_table (
                Company_Full_Name TEXT NOT NULL,
                Last_Price TEXT NULL,
                Shariah TEXT NOT NULL,
                Sector TEXT NOT NULL,
                Company_Key TEXT NOT NULL
            );
        , parameters: None
[2022-10-01 20:50:37,306] {postgres.py:94} INFO - NOTICE:  relation "company_dim_table" already exists, skipping

[2022-10-01 20:50:37,353] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_company_dim_table, execution_date=20221001T204923, start_date=20221001T205037, end_date=20221001T205037
[2022-10-01 20:50:37,446] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-01 20:50:37,525] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
