[2022-10-01 19:51:43,168] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.create_company_dim_table manual__2022-10-01T19:50:36.183945+00:00 [queued]>
[2022-10-01 19:51:43,200] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.create_company_dim_table manual__2022-10-01T19:50:36.183945+00:00 [queued]>
[2022-10-01 19:51:43,200] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 19:51:43,201] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-01 19:51:43,201] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 19:51:43,236] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_company_dim_table> on 2022-10-01 19:50:36.183945+00:00
[2022-10-01 19:51:43,250] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_company_dim_table', 'manual__2022-10-01T19:50:36.183945+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpaqishx7n', '--error-file', '/tmp/tmpcmpi4vq5']
[2022-10-01 19:51:43,246] {standard_task_runner.py:52} INFO - Started process 588 to run task
[2022-10-01 19:51:43,257] {standard_task_runner.py:80} INFO - Job 65: Subtask create_company_dim_table
[2022-10-01 19:51:43,370] {task_command.py:369} INFO - Running <TaskInstance: main_dag.create_company_dim_table manual__2022-10-01T19:50:36.183945+00:00 [running]> on host cb37a969dddb
[2022-10-01 19:51:43,523] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_company_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T19:50:36.183945+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-01T19:50:36.183945+00:00
[2022-10-01 19:51:43,536] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-01 19:51:43,543] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS company_dim_table (
                Company_Full_Name TEXT NOT NULL,
                Shariah TEXT NOT NULL,
                Sector TEXT NOT NULL,
                Company_Key TEXT NOT NULL
            );
        , parameters: None
[2022-10-01 19:51:43,545] {postgres.py:94} INFO - NOTICE:  relation "company_dim_table" already exists, skipping

[2022-10-01 19:51:43,565] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_company_dim_table, execution_date=20221001T195036, start_date=20221001T195143, end_date=20221001T195143
[2022-10-01 19:51:43,599] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-01 19:51:43,677] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
