[2022-10-01 19:49:17,457] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.store_fct_table manual__2022-10-01T19:48:36.834322+00:00 [queued]>
[2022-10-01 19:49:17,482] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.store_fct_table manual__2022-10-01T19:48:36.834322+00:00 [queued]>
[2022-10-01 19:49:17,486] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 19:49:17,487] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-01 19:49:17,487] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 19:49:17,512] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_fct_table> on 2022-10-01 19:48:36.834322+00:00
[2022-10-01 19:49:17,518] {standard_task_runner.py:52} INFO - Started process 539 to run task
[2022-10-01 19:49:17,523] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'store_fct_table', 'manual__2022-10-01T19:48:36.834322+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp2k7bwgan', '--error-file', '/tmp/tmptch9gpnv']
[2022-10-01 19:49:17,524] {standard_task_runner.py:80} INFO - Job 59: Subtask store_fct_table
[2022-10-01 19:49:17,629] {task_command.py:369} INFO - Running <TaskInstance: main_dag.store_fct_table manual__2022-10-01T19:48:36.834322+00:00 [running]> on host cb37a969dddb
[2022-10-01 19:49:17,894] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=store_fct_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T19:48:36.834322+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-01T19:48:36.834322+00:00
[2022-10-01 19:49:17,898] {postgres.py:127} INFO - Running copy expert: COPY fct_table FROM stdin WITH DELIMITER as ',', filename: df_fct_table.csv
[2022-10-01 19:49:17,973] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-01 19:49:18,067] {python.py:173} INFO - Done. Returned value was: None
[2022-10-01 19:49:18,156] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=store_fct_table, execution_date=20221001T194836, start_date=20221001T194917, end_date=20221001T194918
[2022-10-01 19:49:18,296] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-01 19:49:18,603] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
